import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { useAuth } from "@/hooks";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function Home() {
  const { user, isLoading, logout } = useAuth();
  const [loggedOut, setLoggedOut] = useState(false);
  const [countDown, setCountDown] = useState(5);
  const router = useRouter();

  useEffect(() => {
    if (loggedOut) return;
    if (!user && !isLoading && !loggedOut) {
      router.push("/");
      return;
    }

    logout();
    setLoggedOut(true);
  }, [logout, user, isLoading, loggedOut, router]);

  useEffect(() => {
    let countDownTimer: NodeJS.Timeout;

    countDownTimer = setTimeout(() => {
      if (countDown <= 0) {
        router.push("/");
        return;
      }

      setCountDown(countDown - 1);
    }, 1000);

    return () => clearTimeout(countDownTimer);
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>You were logged out!</h1>
          <h2>{countDown}</h2>
        </div>
      </main>
    </>
  );
}
