version: '3'

services:
  db:
    container_name: canwecoop_db
    image: postgres:alpine
    env_file:
      - .env
    restart: on-failure:5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432