["server"]
port=3000
timezone="Europe/Berlin"
frontend_url="http://localhost:3000"
domain="localhost"

["steam"]
api_key=""
sync_interval_seconds=60
sync_cooldown_seconds=300
sync_role="sync_user"
chunk_size=195
default_categories=["Co-op", "LAN Co-op", "Online Co-op", "PvP", "Online PvP", "Shared/Split Screen", "Shared/Split Screen PvP", "Shared/Split Screen Co-op", "Cross-Platform Multiplayer", "Multi-player"]

["database"]
host="localhost"
username="dev"
password="dev"
name="dev"
port=5432
ssl="disable"

["auth"]
secret="supersecret"
origin_cookie_name="origin"
jwt_expires=86400

["auth_cookie"]
name="session"
secure=false
http_only=true
path="/"
expires=3600
max_age=86400

["log"]
log_file="../.temp/log/app.log"
max_size=1
max_backups=3
max_age=28

["mail"]
host="localhost"
port=25
username="noreply@localhost.com"
password=""
from="canwecoop"
to=""
ssl=false
tls=false

["cors"]
enabled=true
allowed_origins=["http://localhost:3000"]
allowed_methods=["GET","POST","PATCH","PUT","DELETE","OPTIONS"]
allowed_headers=["Accept","Authorization","Content-Type","X-CSRF-Token"]
exposed_headers=["Link"]
allowed_credentials=true
