["server"]
port=3000
timezone="Europe/Berlin"

["steam"]
api_key=""
sync_interval_seconds=60
sync_cooldown_seconds=300
sync_role="sync_user"

["database"]
host="localhost"
username="dev"
password="dev"
name="dev"
port=5432
ssl="disable"

["auth"]
secret="supersecret"
auth_cookie_name="session"
origin_cookie_name="origin"
jwt_expires=86400

["log"]
log_file="../.temp/log/app.log"
max_size=1
max_backups=3
max_age=28
