export { ApiClient } from "./apiClient";
export { ClientConfig } from "./getClientConfig";
export { getClientConfig } from "./getClientConfig";
export { getGamesMetaData } from "./getGamesMetaData";
export { getGames } from "./getGames";
export { getFriends } from "./getFriends";
export { updateFriends } from "./updateFriends";
export { sendMail } from "./sendMail";
export type { IGamesMetaData } from "./getGamesMetaData";
export type { ISendMailResponse } from "./sendMail";
export type { IGames } from "./getGames";
export type { IFriends } from "./getFriends";
